export const INICIAR_CONSULTA = 'INICIAR_CONSULTA';
export const CONSULTA_EXITO = 'CONSULTA_EXITO';
export const CONSULTA_ERROR = 'CONSULTA_ERROR';

export const OBTENER_PAISES = 'OBTENER_PAISES';
export const PAISES_EXITO = 'PAISES_EXITO';
export const PAISES_ERROR = 'PAISES_ERROR';

export const OBTENER_GLOBAL = 'OBTENER_GLOBAL';
export const GLOBAL_EXITO = 'GLOBAL_EXITO';
export const GLOBAL_ERROR = 'GLOBAL_ERROR';

export const SUSCRIBIR_CORREO = 'SUSCRIBIR_CORREO';
export const SUSCRIPCION_EXITO = 'SUSCRIPCION_EXITO';
export const SUSCRIPCION_ERROR = 'SUSCRIPCION_ERROR';